//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.API.Endpoint.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.API.Endpoint.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
		#region Application Log
		/// <summary>
		///   Looks up a localized string similar to Invalid application log id: {0}..
		/// </summary>
		public static string ApplicationLog_InvalidId {
            get {
                return ResourceManager.GetString("ApplicationLog_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application log page number: {0}..
        /// </summary>
        public static string ApplicationLog_InvalidPageNumber {
            get {
                return ResourceManager.GetString("ApplicationLog_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application log found with id: {0}..
        /// </summary>
        public static string ApplicationLog_NotFoundId {
            get {
                return ResourceManager.GetString("ApplicationLog_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application logs found..
        /// </summary>
        public static string ApplicationLog_NotFoundList {
            get {
                return ResourceManager.GetString("ApplicationLog_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application log is null..
        /// </summary>
        public static string ApplicationLog_Null {
            get {
                return ResourceManager.GetString("ApplicationLog_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audit log id: {0}..
        /// </summary>
        public static string AuditLog_InvalidId {
            get {
                return ResourceManager.GetString("AuditLog_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audit log page number: {0}..
        /// </summary>
        public static string AuditLog_InvalidPageNumber {
            get {
                return ResourceManager.GetString("AuditLog_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audit log found with id: {0}..
        /// </summary>
        public static string AuditLog_NotFoundId {
            get {
                return ResourceManager.GetString("AuditLog_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audit logs found..
        /// </summary>
        public static string AuditLog_NotFoundList {
            get {
                return ResourceManager.GetString("AuditLog_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit log is null..
        /// </summary>
        public static string AuditLog_Null {
            get {
                return ResourceManager.GetString("AuditLog_Null", resourceCulture);
            }
        }
		#endregion
		#region Auth
		/// <summary>
		///   Looks up a localized string similar to Refresh token expired..
		/// </summary>
		public static string Auth_ExpiredRefreshToken {
            get {
                return ResourceManager.GetString("Auth_ExpiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string Auth_InvalidRefreshToken {
            get {
                return ResourceManager.GetString("Auth_InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login information is null..
        /// </summary>
        public static string Auth_LoginNull {
            get {
                return ResourceManager.GetString("Auth_LoginNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information is null..
        /// </summary>
        public static string Auth_UserInfoNull {
            get {
                return ResourceManager.GetString("Auth_UserInfoNull", resourceCulture);
            }
        }
		#endregion
		#region Email

		/// <summary>
		///   Looks up a localized string similar to To, Subject or Body is empty. Property can not be empty..
		/// </summary>
		public static string Email_Empty {
            get {
                return ResourceManager.GetString("Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is null..
        /// </summary>
        public static string Email_Null {
            get {
                return ResourceManager.GetString("Email_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email template id: {0}..
        /// </summary>
        public static string EmailTemplate_InvalidId {
            get {
                return ResourceManager.GetString("EmailTemplate_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email template page number: {0}..
        /// </summary>
        public static string EmailTemplate_InvalidPageNumber {
            get {
                return ResourceManager.GetString("EmailTemplate_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Id mismatch..
        /// </summary>
        public static string EmailTemplate_Mismatch {
            get {
                return ResourceManager.GetString("EmailTemplate_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found with id: {0}..
        /// </summary>
        public static string EmailTemplate_NotFoundId {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found..
        /// </summary>
        public static string EmailTemplate_NotFoundList {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found with name: {0}..
        /// </summary>
        public static string EmailTemplate_NotFoundName {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTemplate is null..
        /// </summary>
        public static string EmailTemplate_Null {
            get {
                return ResourceManager.GetString("EmailTemplate_Null", resourceCulture);
            }
        }
		#endregion
		#region Mobile

		/// <summary>
		///   Looks up a localized string similar to Invalid hash provided..
		/// </summary>
		public static string InvalidHash {
            get {
                return ResourceManager.GetString("InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password information is null..
        /// </summary>
        public static string MobileAuth_ChangePasswordNull {
            get {
                return ResourceManager.GetString("MobileAuth_ChangePasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration information is null..
        /// </summary>
        public static string MobileAuth_RegisterNull {
            get {
                return ResourceManager.GetString("MobileAuth_RegisterNull", resourceCulture);
            }
        }

		/// <summary>
		///   Looks up a localized string similar to To or Content is empty. Property can not be empty..
		/// </summary>
		public static string SMS_Empty
		{
			get
			{
				return ResourceManager.GetString("SMS_Empty", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to SMS is null..
		/// </summary>
		public static string SMS_Null
		{
			get
			{
				return ResourceManager.GetString("SMS_Null", resourceCulture);
			}
		}
		#endregion
		#region Pie
		/// <summary>
		///   Looks up a localized string similar to The pie &apos;{0}&apos; already exists..
		/// </summary>
		public static string Pie_Duplicate {
            get {
                return ResourceManager.GetString("Pie_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie category id: {0}..
        /// </summary>
        public static string Pie_InvalidCategoryId {
            get {
                return ResourceManager.GetString("Pie_InvalidCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie id: {0}..
        /// </summary>
        public static string Pie_InvalidId {
            get {
                return ResourceManager.GetString("Pie_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie page number: {0}..
        /// </summary>
        public static string Pie_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Pie_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Id mismatch..
        /// </summary>
        public static string Pie_Mismatch {
            get {
                return ResourceManager.GetString("Pie_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pie found with category id: {0}..
        /// </summary>
        public static string Pie_NotFoundCategoryId {
            get {
                return ResourceManager.GetString("Pie_NotFoundCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pie found with id: {0}..
        /// </summary>
        public static string Pie_NotFoundId {
            get {
                return ResourceManager.GetString("Pie_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pies found..
        /// </summary>
        public static string Pie_NotFoundList {
            get {
                return ResourceManager.GetString("Pie_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie is null..
        /// </summary>
        public static string Pie_Null {
            get {
                return ResourceManager.GetString("Pie_Null", resourceCulture);
            }
        }
		#endregion

		#region Category

		/// <summary>
		///   Looks up a localized string similar to The category &apos;{0}&apos; already exists..
		/// </summary>
		public static string Category_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Category_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid category id: {0}..
		/// </summary>
		public static string Category_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Category_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid category page number: {0}..
		/// </summary>
		public static string Category_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Category_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Category Id mismatch..
		/// </summary>
		public static string Category_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Category_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Category_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Category_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No category found with id: {0}..
		/// </summary>
		public static string Category_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Category_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Category_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Category_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Category is null..
		/// </summary>
		public static string Category_Null
		{
			get
			{
				return ResourceManager.GetString("Category_Null", resourceCulture);
			}
		}

		#endregion
		#region Degree

		/// <summary>
		///   Looks up a localized string similar to The Degree &apos;{0}&apos; already exists..
		/// </summary>
		public static string Degree_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Degree_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Degree id: {0}..
		/// </summary>
		public static string Degree_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Degree_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Degree page number: {0}..
		/// </summary>
		public static string Degree_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Degree_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Degree Id mismatch..
		/// </summary>
		public static string Degree_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Degree_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Degree_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Degree_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Degree found with id: {0}..
		/// </summary>
		public static string Degree_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Degree_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Degree_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Degree_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Degree is null..
		/// </summary>
		public static string Degree_Null
		{
			get
			{
				return ResourceManager.GetString("Degree_Null", resourceCulture);
			}
		}


		#endregion

		#region BAASection

		/// <summary>
		///   Looks up a localized string similar to The BAASection &apos;{0}&apos; already exists..
		/// </summary>
		public static string BAASection_Duplicate
		{
			get
			{
				return ResourceManager.GetString("BAASection_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid BAASection id: {0}..
		/// </summary>
		public static string BAASection_InvalidId
		{
			get
			{
				return ResourceManager.GetString("BAASection_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid BAASection page number: {0}..
		/// </summary>
		public static string BAASection_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("BAASection_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to BAASection Id mismatch..
		/// </summary>
		public static string BAASection_Mismatch
		{
			get
			{
				return ResourceManager.GetString("BAASection_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string BAASection_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("BAASection_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No BAASection found with id: {0}..
		/// </summary>
		public static string BAASection_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("BAASection_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string BAASection_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("BAASection_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to BAASection is null..
		/// </summary>
		public static string BAASection_Null
		{
			get
			{
				return ResourceManager.GetString("BAASection_Null", resourceCulture);
			}
		}


		#endregion
		#region BIAnnual

		/// <summary>
		///   Looks up a localized string similar to The BIAnnual &apos;{0}&apos; already exists..
		/// </summary>
		public static string BIAnnual_Duplicate
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid BIAnnual id: {0}..
		/// </summary>
		public static string BIAnnual_InvalidId
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid BIAnnual page number: {0}..
		/// </summary>
		public static string BIAnnual_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to BIAnnual Id mismatch..
		/// </summary>
		public static string BIAnnual_Mismatch
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string BIAnnual_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No BIAnnual found with id: {0}..
		/// </summary>
		public static string BIAnnual_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string BIAnnual_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to BIAnnual is null..
		/// </summary>
		public static string BIAnnual_Null
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Null", resourceCulture);
			}
		}


		#endregion
		#region Brigade

		/// <summary>
		///   Looks up a localized string similar to The Brigade &apos;{0}&apos; already exists..
		/// </summary>
		public static string Brigade_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Brigade_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Brigade id: {0}..
		/// </summary>
		public static string Brigade_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Brigade_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Brigade page number: {0}..
		/// </summary>
		public static string Brigade_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Brigade_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Brigade Id mismatch..
		/// </summary>
		public static string Brigade_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Brigade_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Brigade_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Brigade_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Brigade found with id: {0}..
		/// </summary>
		public static string Brigade_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Brigade_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Brigade_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Brigade_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Brigade is null..
		/// </summary>
		public static string Brigade_Null
		{
			get
			{
				return ResourceManager.GetString("Brigade_Null", resourceCulture);
			}
		}


		#endregion
		#region Certificate

		/// <summary>
		///   Looks up a localized string similar to The Certificate &apos;{0}&apos; already exists..
		/// </summary>
		public static string Certificate_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Certificate_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Certificate id: {0}..
		/// </summary>
		public static string Certificate_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Certificate_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Certificate page number: {0}..
		/// </summary>
		public static string Certificate_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Certificate_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Certificate Id mismatch..
		/// </summary>
		public static string Certificate_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Certificate_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Certificate_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Certificate_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Certificate found with id: {0}..
		/// </summary>
		public static string Certificate_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Certificate_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Certificate_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Certificate_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Certificate is null..
		/// </summary>
		public static string Certificate_Null
		{
			get
			{
				return ResourceManager.GetString("Certificate_Null", resourceCulture);
			}
		}


		#endregion
		#region CertificateAuthority

		/// <summary>
		///   Looks up a localized string similar to The CertificateAuthority &apos;{0}&apos; already exists..
		/// </summary>
		public static string CertificateAuthority_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid CertificateAuthority id: {0}..
		/// </summary>
		public static string CertificateAuthority_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid CertificateAuthority page number: {0}..
		/// </summary>
		public static string CertificateAuthority_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CertificateAuthority Id mismatch..
		/// </summary>
		public static string CertificateAuthority_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string CertificateAuthority_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No CertificateAuthority found with id: {0}..
		/// </summary>
		public static string CertificateAuthority_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string CertificateAuthority_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CertificateAuthority is null..
		/// </summary>
		public static string CertificateAuthority_Null
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Null", resourceCulture);
			}
		}


		#endregion
		#region CivilInstitution

		/// <summary>
		///   Looks up a localized string similar to The CivilInstitution &apos;{0}&apos; already exists..
		/// </summary>
		public static string CivilInstitution_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid CivilInstitution id: {0}..
		/// </summary>
		public static string CivilInstitution_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid CivilInstitution page number: {0}..
		/// </summary>
		public static string CivilInstitution_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CivilInstitution Id mismatch..
		/// </summary>
		public static string CivilInstitution_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string CivilInstitution_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No CivilInstitution found with id: {0}..
		/// </summary>
		public static string CivilInstitution_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string CivilInstitution_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CivilInstitution is null..
		/// </summary>
		public static string CivilInstitution_Null
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Null", resourceCulture);
			}
		}


		#endregion
		#region Company

		/// <summary>
		///   Looks up a localized string similar to The Company &apos;{0}&apos; already exists..
		/// </summary>
		public static string Company_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Company_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Company id: {0}..
		/// </summary>
		public static string Company_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Company_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Company page number: {0}..
		/// </summary>
		public static string Company_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Company_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Company Id mismatch..
		/// </summary>
		public static string Company_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Company_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Company_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Company_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Company found with id: {0}..
		/// </summary>
		public static string Company_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Company_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Company_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Company_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Company is null..
		/// </summary>
		public static string Company_Null
		{
			get
			{
				return ResourceManager.GetString("Company_Null", resourceCulture);
			}
		}


		#endregion
		#region Country

		/// <summary>
		///   Looks up a localized string similar to The Country &apos;{0}&apos; already exists..
		/// </summary>
		public static string Country_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Country_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Country id: {0}..
		/// </summary>
		public static string Country_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Country_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Country page number: {0}..
		/// </summary>
		public static string Country_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Country_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Country Id mismatch..
		/// </summary>
		public static string Country_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Country_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Country_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Country_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Country found with id: {0}..
		/// </summary>
		public static string Country_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Country_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Country_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Country_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Country is null..
		/// </summary>
		public static string Country_Null
		{
			get
			{
				return ResourceManager.GetString("Country_Null", resourceCulture);
			}
		}


		#endregion
		#region Course

		/// <summary>
		///   Looks up a localized string similar to The Course &apos;{0}&apos; already exists..
		/// </summary>
		public static string Course_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Course_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Course id: {0}..
		/// </summary>
		public static string Course_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Course_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Course page number: {0}..
		/// </summary>
		public static string Course_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Course_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Course Id mismatch..
		/// </summary>
		public static string Course_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Course_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Course_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Course_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Course found with id: {0}..
		/// </summary>
		public static string Course_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Course_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Course_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Course_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Course is null..
		/// </summary>
		public static string Course_Null
		{
			get
			{
				return ResourceManager.GetString("Course_Null", resourceCulture);
			}
		}


		#endregion
		#region Duration

		/// <summary>
		///   Looks up a localized string similar to The Duration &apos;{0}&apos; already exists..
		/// </summary>
		public static string Duration_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Duration_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Duration id: {0}..
		/// </summary>
		public static string Duration_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Duration_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Duration page number: {0}..
		/// </summary>
		public static string Duration_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Duration_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Duration Id mismatch..
		/// </summary>
		public static string Duration_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Duration_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Duration_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Duration_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Duration found with id: {0}..
		/// </summary>
		public static string Duration_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Duration_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Duration_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Duration_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Duration is null..
		/// </summary>
		public static string Duration_Null
		{
			get
			{
				return ResourceManager.GetString("Duration_Null", resourceCulture);
			}
		}


		#endregion
		#region MilitaryInstitution

		/// <summary>
		///   Looks up a localized string similar to The MilitaryInstitution &apos;{0}&apos; already exists..
		/// </summary>
		public static string MilitaryInstitution_Duplicate
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid MilitaryInstitution id: {0}..
		/// </summary>
		public static string MilitaryInstitution_InvalidId
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid MilitaryInstitution page number: {0}..
		/// </summary>
		public static string MilitaryInstitution_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MilitaryInstitution Id mismatch..
		/// </summary>
		public static string MilitaryInstitution_Mismatch
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string MilitaryInstitution_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No MilitaryInstitution found with id: {0}..
		/// </summary>
		public static string MilitaryInstitution_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string MilitaryInstitution_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MilitaryInstitution is null..
		/// </summary>
		public static string MilitaryInstitution_Null
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Null", resourceCulture);
			}
		}


		#endregion
		#region Platoon

		/// <summary>
		///   Looks up a localized string similar to The Platoon &apos;{0}&apos; already exists..
		/// </summary>
		public static string Platoon_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Platoon_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Platoon id: {0}..
		/// </summary>
		public static string Platoon_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Platoon_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Platoon page number: {0}..
		/// </summary>
		public static string Platoon_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Platoon_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Platoon Id mismatch..
		/// </summary>
		public static string Platoon_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Platoon_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Platoon_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Platoon_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Platoon found with id: {0}..
		/// </summary>
		public static string Platoon_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Platoon_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Platoon_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Platoon_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Platoon is null..
		/// </summary>
		public static string Platoon_Null
		{
			get
			{
				return ResourceManager.GetString("Platoon_Null", resourceCulture);
			}
		}


		#endregion
		#region Qualification

		/// <summary>
		///   Looks up a localized string similar to The Qualification &apos;{0}&apos; already exists..
		/// </summary>
		public static string Qualification_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Qualification_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Qualification id: {0}..
		/// </summary>
		public static string Qualification_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Qualification_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Qualification page number: {0}..
		/// </summary>
		public static string Qualification_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Qualification_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Qualification Id mismatch..
		/// </summary>
		public static string Qualification_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Qualification_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Qualification_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Qualification_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Qualification found with id: {0}..
		/// </summary>
		public static string Qualification_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Qualification_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Qualification_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Qualification_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Qualification is null..
		/// </summary>
		public static string Qualification_Null
		{
			get
			{
				return ResourceManager.GetString("Qualification_Null", resourceCulture);
			}
		}


		#endregion
		#region Rank

		/// <summary>
		///   Looks up a localized string similar to The Rank &apos;{0}&apos; already exists..
		/// </summary>
		public static string Rank_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Rank_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Rank id: {0}..
		/// </summary>
		public static string Rank_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Rank_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Rank page number: {0}..
		/// </summary>
		public static string Rank_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Rank_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Rank Id mismatch..
		/// </summary>
		public static string Rank_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Rank_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Rank_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Rank_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Rank found with id: {0}..
		/// </summary>
		public static string Rank_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Rank_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Rank_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Rank_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Rank is null..
		/// </summary>
		public static string Rank_Null
		{
			get
			{
				return ResourceManager.GetString("Rank_Null", resourceCulture);
			}
		}


		#endregion
		#region Trade

		/// <summary>
		///   Looks up a localized string similar to The Trade &apos;{0}&apos; already exists..
		/// </summary>
		public static string Trade_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Trade_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Trade id: {0}..
		/// </summary>
		public static string Trade_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Trade_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Trade page number: {0}..
		/// </summary>
		public static string Trade_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Trade_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Trade Id mismatch..
		/// </summary>
		public static string Trade_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Trade_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Trade_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Trade_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Trade found with id: {0}..
		/// </summary>
		public static string Trade_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Trade_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Trade_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Trade_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Trade is null..
		/// </summary>
		public static string Trade_Null
		{
			get
			{
				return ResourceManager.GetString("Trade_Null", resourceCulture);
			}
		}


		#endregion
		#region Training

		/// <summary>
		///   Looks up a localized string similar to The Training &apos;{0}&apos; already exists..
		/// </summary>
		public static string Training_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Training_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Training id: {0}..
		/// </summary>
		public static string Training_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Training_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Training page number: {0}..
		/// </summary>
		public static string Training_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Training_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Training Id mismatch..
		/// </summary>
		public static string Training_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Training_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Training_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Training_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Training found with id: {0}..
		/// </summary>
		public static string Training_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Training_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Training_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Training_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Training is null..
		/// </summary>
		public static string Training_Null
		{
			get
			{
				return ResourceManager.GetString("Training_Null", resourceCulture);
			}
		}


		#endregion
		#region Unit

		/// <summary>
		///   Looks up a localized string similar to The Unit &apos;{0}&apos; already exists..
		/// </summary>
		public static string Unit_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Unit_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Unit id: {0}..
		/// </summary>
		public static string Unit_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Unit_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Unit page number: {0}..
		/// </summary>
		public static string Unit_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Unit_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unit Id mismatch..
		/// </summary>
		public static string Unit_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Unit_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Unit_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Unit_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Unit found with id: {0}..
		/// </summary>
		public static string Unit_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Unit_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Unit_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Unit_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unit is null..
		/// </summary>
		public static string Unit_Null
		{
			get
			{
				return ResourceManager.GetString("Unit_Null", resourceCulture);
			}
		}


		#endregion
		#region Applicant

		/// <summary>
		///   Looks up a localized string similar to The Applicant &apos;{0}&apos; already exists..
		/// </summary>
		public static string Applicant_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Applicant_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Applicant id: {0}..
		/// </summary>
		public static string Applicant_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Applicant_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid Applicant page number: {0}..
		/// </summary>
		public static string Applicant_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Applicant_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Applicant Id mismatch..
		/// </summary>
		public static string Applicant_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Applicant_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string Applicant_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("Applicant_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Applicant found with id: {0}..
		/// </summary>
		public static string Applicant_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Applicant_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string Applicant_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Applicant_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Applicant is null..
		/// </summary>
		public static string Applicant_Null
		{
			get
			{
				return ResourceManager.GetString("Applicant_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantAddlQualification

		/// <summary>
		///   Looks up a localized string similar to The ApplicantAddlQualification &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantAddlQualification_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantAddlQualification_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantAddlQualification id: {0}..
		/// </summary>
		public static string ApplicantAddlQualification_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantAddlQualification_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantAddlQualification page number: {0}..
		/// </summary>
		public static string ApplicantAddlQualification_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantAddlQualification_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantAddlQualification Id mismatch..
		/// </summary>
		public static string ApplicantAddlQualification_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantAddlQualification_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantAddlQualification_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantAddlQualification_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantAddlQualification found with id: {0}..
		/// </summary>
		public static string ApplicantAddlQualification_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantAddlQualification_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantAddlQualification_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantAddlQualification_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantAddlQualification is null..
		/// </summary>
		public static string ApplicantAddlQualification_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantAddlQualification_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantAssultCourse

		/// <summary>
		///   Looks up a localized string similar to The ApplicantAssultCourse &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantAssultCourse_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantAssultCourse_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantAssultCourse id: {0}..
		/// </summary>
		public static string ApplicantAssultCourse_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantAssultCourse_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantAssultCourse page number: {0}..
		/// </summary>
		public static string ApplicantAssultCourse_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantAssultCourse_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantAssultCourse Id mismatch..
		/// </summary>
		public static string ApplicantAssultCourse_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantAssultCourse_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantAssultCourse_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantAssultCourse_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantAssultCourse found with id: {0}..
		/// </summary>
		public static string ApplicantAssultCourse_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantAssultCourse_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantAssultCourse_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantAssultCourse_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantAssultCourse is null..
		/// </summary>
		public static string ApplicantAssultCourse_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantAssultCourse_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantCadre

		/// <summary>
		///   Looks up a localized string similar to The ApplicantCadre &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantCadre_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantCadre_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantCadre id: {0}..
		/// </summary>
		public static string ApplicantCadre_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantCadre_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantCadre page number: {0}..
		/// </summary>
		public static string ApplicantCadre_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantCadre_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantCadre Id mismatch..
		/// </summary>
		public static string ApplicantCadre_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantCadre_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantCadre_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantCadre_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantCadre found with id: {0}..
		/// </summary>
		public static string ApplicantCadre_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantCadre_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantCadre_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantCadre_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantCadre is null..
		/// </summary>
		public static string ApplicantCadre_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantCadre_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantCertification

		/// <summary>
		///   Looks up a localized string similar to The ApplicantCertification &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantCertification_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantCertification_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantCertification id: {0}..
		/// </summary>
		public static string ApplicantCertification_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantCertification_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantCertification page number: {0}..
		/// </summary>
		public static string ApplicantCertification_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantCertification_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantCertification Id mismatch..
		/// </summary>
		public static string ApplicantCertification_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantCertification_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantCertification_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantCertification_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantCertification found with id: {0}..
		/// </summary>
		public static string ApplicantCertification_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantCertification_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantCertification_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantCertification_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantCertification is null..
		/// </summary>
		public static string ApplicantCertification_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantCertification_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantCivilEducation

		/// <summary>
		///   Looks up a localized string similar to The ApplicantCivilEducation &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantCivilEducation_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantCivilEducation_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantCivilEducation id: {0}..
		/// </summary>
		public static string ApplicantCivilEducation_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantCivilEducation_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantCivilEducation page number: {0}..
		/// </summary>
		public static string ApplicantCivilEducation_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantCivilEducation_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantCivilEducation Id mismatch..
		/// </summary>
		public static string ApplicantCivilEducation_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantCivilEducation_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantCivilEducation_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantCivilEducation_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantCivilEducation found with id: {0}..
		/// </summary>
		public static string ApplicantCivilEducation_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantCivilEducation_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantCivilEducation_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantCivilEducation_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantCivilEducation is null..
		/// </summary>
		public static string ApplicantCivilEducation_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantCivilEducation_Null", resourceCulture);
			}
		}


		#endregion
		#region ApplicantCompetition

		/// <summary>
		///   Looks up a localized string similar to The ApplicantCompetition &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantCompetition_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantCompetition_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantCompetition id: {0}..
		/// </summary>
		public static string ApplicantCompetition_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantCompetition_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantCompetition page number: {0}..
		/// </summary>
		public static string ApplicantCompetition_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantCompetition_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantCompetition Id mismatch..
		/// </summary>
		public static string ApplicantCompetition_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantCompetition_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantCompetition_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantCompetition_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantCompetition found with id: {0}..
		/// </summary>
		public static string ApplicantCompetition_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantCompetition_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantCompetition_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantCompetition_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantCompetition is null..
		/// </summary>
		public static string ApplicantCompetition_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantCompetition_Null", resourceCulture);
			}
		}


		#endregion
		#region ApplicantDiscipline

		/// <summary>
		///   Looks up a localized string similar to The ApplicantDiscipline &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantDiscipline_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantDiscipline_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantDiscipline id: {0}..
		/// </summary>
		public static string ApplicantDiscipline_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantDiscipline_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantDiscipline page number: {0}..
		/// </summary>
		public static string ApplicantDiscipline_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantDiscipline_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantDiscipline Id mismatch..
		/// </summary>
		public static string ApplicantDiscipline_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantDiscipline_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantDiscipline_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantDiscipline_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantDiscipline found with id: {0}..
		/// </summary>
		public static string ApplicantDiscipline_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantDiscipline_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantDiscipline_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantDiscipline_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantDiscipline is null..
		/// </summary>
		public static string ApplicantDiscipline_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantDiscipline_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantIPFT

		/// <summary>
		///   Looks up a localized string similar to The ApplicantIPFT &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantIPFT_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantIPFT_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantIPFT id: {0}..
		/// </summary>
		public static string ApplicantIPFT_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantIPFT_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantIPFT page number: {0}..
		/// </summary>
		public static string ApplicantIPFT_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantIPFT_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantIPFT Id mismatch..
		/// </summary>
		public static string ApplicantIPFT_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantIPFT_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantIPFT_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantIPFT_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantIPFT found with id: {0}..
		/// </summary>
		public static string ApplicantIPFT_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantIPFT_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantIPFT_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantIPFT_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantIPFT is null..
		/// </summary>
		public static string ApplicantIPFT_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantIPFT_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantMilitaryTraining

		/// <summary>
		///   Looks up a localized string similar to The ApplicantMilitaryTraining &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantMilitaryTraining_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantMilitaryTraining_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantMilitaryTraining id: {0}..
		/// </summary>
		public static string ApplicantMilitaryTraining_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantMilitaryTraining_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantMilitaryTraining page number: {0}..
		/// </summary>
		public static string ApplicantMilitaryTraining_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantMilitaryTraining_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantMilitaryTraining Id mismatch..
		/// </summary>
		public static string ApplicantMilitaryTraining_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantMilitaryTraining_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantMilitaryTraining_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantMilitaryTraining_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantMilitaryTraining found with id: {0}..
		/// </summary>
		public static string ApplicantMilitaryTraining_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantMilitaryTraining_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantMilitaryTraining_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantMilitaryTraining_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantMilitaryTraining is null..
		/// </summary>
		public static string ApplicantMilitaryTraining_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantMilitaryTraining_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantQuizCompetition

		/// <summary>
		///   Looks up a localized string similar to The ApplicantQuizCompetition &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantQuizCompetition_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantQuizCompetition_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantQuizCompetition id: {0}..
		/// </summary>
		public static string ApplicantQuizCompetition_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantQuizCompetition_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantQuizCompetition page number: {0}..
		/// </summary>
		public static string ApplicantQuizCompetition_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantQuizCompetition_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantQuizCompetition Id mismatch..
		/// </summary>
		public static string ApplicantQuizCompetition_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantQuizCompetition_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantQuizCompetition_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantQuizCompetition_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantQuizCompetition found with id: {0}..
		/// </summary>
		public static string ApplicantQuizCompetition_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantQuizCompetition_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantQuizCompetition_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantQuizCompetition_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantQuizCompetition is null..
		/// </summary>
		public static string ApplicantQuizCompetition_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantQuizCompetition_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantRET

		/// <summary>
		///   Looks up a localized string similar to The ApplicantRET &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantRET_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantRET_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantRET id: {0}..
		/// </summary>
		public static string ApplicantRET_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantRET_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantRET page number: {0}..
		/// </summary>
		public static string ApplicantRET_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantRET_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantRET Id mismatch..
		/// </summary>
		public static string ApplicantRET_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantRET_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantRET_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantRET_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantRET found with id: {0}..
		/// </summary>
		public static string ApplicantRET_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantRET_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantRET_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantRET_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantRET is null..
		/// </summary>
		public static string ApplicantRET_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantRET_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantRoleMapping

		/// <summary>
		///   Looks up a localized string similar to The ApplicantRoleMapping &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantRoleMapping_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantRoleMapping_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantRoleMapping id: {0}..
		/// </summary>
		public static string ApplicantRoleMapping_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantRoleMapping_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantRoleMapping page number: {0}..
		/// </summary>
		public static string ApplicantRoleMapping_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantRoleMapping_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantRoleMapping Id mismatch..
		/// </summary>
		public static string ApplicantRoleMapping_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantRoleMapping_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantRoleMapping_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantRoleMapping_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantRoleMapping found with id: {0}..
		/// </summary>
		public static string ApplicantRoleMapping_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantRoleMapping_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantRoleMapping_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantRoleMapping_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantRoleMapping is null..
		/// </summary>
		public static string ApplicantRoleMapping_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantRoleMapping_Null", resourceCulture);
			}
		}


		#endregion

		#region ApplicantGPT

		/// <summary>
		///   Looks up a localized string similar to The ApplicantGPT &apos;{0}&apos; already exists..
		/// </summary>
		public static string ApplicantGPT_Duplicate
		{
			get
			{
				return ResourceManager.GetString("ApplicantGPT_Duplicate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantGPT id: {0}..
		/// </summary>
		public static string ApplicantGPT_InvalidId
		{
			get
			{
				return ResourceManager.GetString("ApplicantGPT_InvalidId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid ApplicantGPT page number: {0}..
		/// </summary>
		public static string ApplicantGPT_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("ApplicantGPT_InvalidPageNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantGPT Id mismatch..
		/// </summary>
		public static string ApplicantGPT_Mismatch
		{
			get
			{
				return ResourceManager.GetString("ApplicantGPT_Mismatch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
		/// </summary>
		public static string ApplicantGPT_NotFoundGetCategoriesWithPies
		{
			get
			{
				return ResourceManager.GetString("ApplicantGPT_NotFoundGetCategoriesWithPies", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No ApplicantGPT found with id: {0}..
		/// </summary>
		public static string ApplicantGPT_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("ApplicantGPT_NotFoundId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No categories found..
		/// </summary>
		public static string ApplicantGPT_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("ApplicantGPT_NotFoundList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ApplicantGPT is null..
		/// </summary>
		public static string ApplicantGPT_Null
		{
			get
			{
				return ResourceManager.GetString("ApplicantGPT_Null", resourceCulture);
			}
		}


		#endregion
		#region Deshboard
		
		/// <summary>
		///   Looks up a localized string similar to Deshboard Data Not Found..
		/// </summary>
		public static string Deshboard_DataNotFound
		{
			get
			{
				return ResourceManager.GetString("Deshboard_DataNotFound", resourceCulture);
			}
		}
		#endregion


	}
}
