//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.API.Endpoint.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.API.Endpoint.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting application log..
        /// </summary>
        public static string ApplicationLog_Delete {
            get {
                return ResourceManager.GetString("ApplicationLog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving application log by id..
        /// </summary>
        public static string ApplicationLog_Id {
            get {
                return ResourceManager.GetString("ApplicationLog_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving application logs..
        /// </summary>
        public static string ApplicationLog_List {
            get {
                return ResourceManager.GetString("ApplicationLog_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting audit log..
        /// </summary>
        public static string AuditLog_Delete {
            get {
                return ResourceManager.GetString("AuditLog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving audit log by id..
        /// </summary>
        public static string AuditLog_Id {
            get {
                return ResourceManager.GetString("AuditLog_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting new audit log..
        /// </summary>
        public static string AuditLog_Insert {
            get {
                return ResourceManager.GetString("AuditLog_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving audit logs..
        /// </summary>
        public static string AuditLog_List {
            get {
                return ResourceManager.GetString("AuditLog_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting current user information..
        /// </summary>
        public static string Auth_GetCurrentUser {
            get {
                return ResourceManager.GetString("Auth_GetCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting token..
        /// </summary>
        public static string Auth_GetToken {
            get {
                return ResourceManager.GetString("Auth_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging user..
        /// </summary>
        public static string Auth_Login {
            get {
                return ResourceManager.GetString("Auth_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting refresh token..
        /// </summary>
        public static string Auth_RefreshToken {
            get {
                return ResourceManager.GetString("Auth_RefreshToken", resourceCulture);
            }
        }

		#region Category
		/// <summary>
		///   Looks up a localized string similar to Error retrieving categories with pies..
		/// </summary>
		public static string Category_CategoriesWithPies {
            get {
                return ResourceManager.GetString("Category_CategoriesWithPies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting category..
        /// </summary>
        public static string Category_Delete {
            get {
                return ResourceManager.GetString("Category_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving category by id..
        /// </summary>
        public static string Category_Id {
            get {
                return ResourceManager.GetString("Category_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting new category..
        /// </summary>
        public static string Category_Insert {
            get {
                return ResourceManager.GetString("Category_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving categories..
        /// </summary>
        public static string Category_List {
            get {
                return ResourceManager.GetString("Category_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating category..
        /// </summary>
        public static string Category_Update {
            get {
                return ResourceManager.GetString("Category_Update", resourceCulture);
            }
        }
		#endregion

		/// <summary>
		///   Looks up a localized string similar to Email could not be sent..
		/// </summary>
		public static string Email_Send {
            get {
                return ResourceManager.GetString("Email_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving email templates..
        /// </summary>
        public static string EmailTemplate_List {
            get {
                return ResourceManager.GetString("EmailTemplate_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating email template..
        /// </summary>
        public static string EmailTemplate_Update {
            get {
                return ResourceManager.GetString("EmailTemplate_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing password..
        /// </summary>
        public static string MobileAuth_ChangePassword {
            get {
                return ResourceManager.GetString("MobileAuth_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in forgot password..
        /// </summary>
        public static string MobileAuth_ForgotPassword {
            get {
                return ResourceManager.GetString("MobileAuth_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting current user information..
        /// </summary>
        public static string MobileAuth_GetCurrentUser {
            get {
                return ResourceManager.GetString("MobileAuth_GetCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting token..
        /// </summary>
        public static string MobileAuth_GetToken {
            get {
                return ResourceManager.GetString("MobileAuth_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging user..
        /// </summary>
        public static string MobileAuth_Login {
            get {
                return ResourceManager.GetString("MobileAuth_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error registering user..
        /// </summary>
        public static string MobileAuth_Register {
            get {
                return ResourceManager.GetString("MobileAuth_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving pie by category id..
        /// </summary>
        public static string Pie_CategoryId {
            get {
                return ResourceManager.GetString("Pie_CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting pie..
        /// </summary>
        public static string Pie_Delete {
            get {
                return ResourceManager.GetString("Pie_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving pie by id..
        /// </summary>
        public static string Pie_Id {
            get {
                return ResourceManager.GetString("Pie_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting new pie..
        /// </summary>
        public static string Pie_Insert {
            get {
                return ResourceManager.GetString("Pie_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving pies..
        /// </summary>
        public static string Pie_List {
            get {
                return ResourceManager.GetString("Pie_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating pie..
        /// </summary>
        public static string Pie_Update {
            get {
                return ResourceManager.GetString("Pie_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS could not be sent..
        /// </summary>
        public static string SMS_Send {
            get {
                return ResourceManager.GetString("SMS_Send", resourceCulture);
            }
        }


		#region Brigade

		public static string Brigade_Delete
		{
			get
			{
				return ResourceManager.GetString("Brigade_Delete", resourceCulture);
			}
		}


		public static string Brigade_Id
		{
			get
			{
				return ResourceManager.GetString("Brigade_Id", resourceCulture);
			}
		}


		public static string Brigade_Insert
		{
			get
			{
				return ResourceManager.GetString("Brigade_Insert", resourceCulture);
			}
		}


		public static string Brigade_List
		{
			get
			{
				return ResourceManager.GetString("Brigade_List", resourceCulture);
			}
		}


		public static string Brigade_Update
		{
			get
			{
				return ResourceManager.GetString("Brigade_Update", resourceCulture);
			}
		}
		#endregion

		#region BAASection

		public static string BAASection_Delete
		{
			get
			{
				return ResourceManager.GetString("BAASection_Delete", resourceCulture);
			}
		}


		public static string BAASection_Id
		{
			get
			{
				return ResourceManager.GetString("BAASection_Id", resourceCulture);
			}
		}


		public static string BAASection_Insert
		{
			get
			{
				return ResourceManager.GetString("BAASection_Insert", resourceCulture);
			}
		}


		public static string BAASection_List
		{
			get
			{
				return ResourceManager.GetString("BAASection_List", resourceCulture);
			}
		}


		public static string BAASection_Update
		{
			get
			{
				return ResourceManager.GetString("BAASection_Update", resourceCulture);
			}
		}
		#endregion

		#region BIAnnual

		public static string BIAnnual_Delete
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Delete", resourceCulture);
			}
		}


		public static string BIAnnual_Id
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Id", resourceCulture);
			}
		}


		public static string BIAnnual_Insert
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Insert", resourceCulture);
			}
		}


		public static string BIAnnual_List
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_List", resourceCulture);
			}
		}


		public static string BIAnnual_Update
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Update", resourceCulture);
			}
		}
		#endregion

		#region Certificate

		public static string Certificate_Delete
		{
			get
			{
				return ResourceManager.GetString("Certificate_Delete", resourceCulture);
			}
		}


		public static string Certificate_Id
		{
			get
			{
				return ResourceManager.GetString("Certificate_Id", resourceCulture);
			}
		}


		public static string Certificate_Insert
		{
			get
			{
				return ResourceManager.GetString("Certificate_Insert", resourceCulture);
			}
		}


		public static string Certificate_List
		{
			get
			{
				return ResourceManager.GetString("Certificate_List", resourceCulture);
			}
		}


		public static string Certificate_Update
		{
			get
			{
				return ResourceManager.GetString("Certificate_Update", resourceCulture);
			}
		}
		#endregion

		#region CertificateAuthority

		public static string CertificateAuthority_Delete
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Delete", resourceCulture);
			}
		}


		public static string CertificateAuthority_Id
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Id", resourceCulture);
			}
		}


		public static string CertificateAuthority_Insert
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Insert", resourceCulture);
			}
		}


		public static string CertificateAuthority_List
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_List", resourceCulture);
			}
		}


		public static string CertificateAuthority_Update
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Update", resourceCulture);
			}
		}
		#endregion

		#region Company

		public static string Company_Delete
		{
			get
			{
				return ResourceManager.GetString("Company_Delete", resourceCulture);
			}
		}


		public static string Company_Id
		{
			get
			{
				return ResourceManager.GetString("Company_Id", resourceCulture);
			}
		}


		public static string Company_Insert
		{
			get
			{
				return ResourceManager.GetString("Company_Insert", resourceCulture);
			}
		}


		public static string Company_List
		{
			get
			{
				return ResourceManager.GetString("Company_List", resourceCulture);
			}
		}


		public static string Company_Update
		{
			get
			{
				return ResourceManager.GetString("Company_Update", resourceCulture);
			}
		}
		#endregion

		#region Course

		public static string Course_Delete
		{
			get
			{
				return ResourceManager.GetString("Course_Delete", resourceCulture);
			}
		}


		public static string Course_Id
		{
			get
			{
				return ResourceManager.GetString("Course_Id", resourceCulture);
			}
		}


		public static string Course_Insert
		{
			get
			{
				return ResourceManager.GetString("Course_Insert", resourceCulture);
			}
		}


		public static string Course_List
		{
			get
			{
				return ResourceManager.GetString("Course_List", resourceCulture);
			}
		}


		public static string Course_Update
		{
			get
			{
				return ResourceManager.GetString("Course_Update", resourceCulture);
			}
		}
		#endregion

		#region Degree

		public static string Degree_Delete
		{
			get
			{
				return ResourceManager.GetString("Degree_Delete", resourceCulture);
			}
		}


		public static string Degree_Id
		{
			get
			{
				return ResourceManager.GetString("Degree_Id", resourceCulture);
			}
		}


		public static string Degree_Insert
		{
			get
			{
				return ResourceManager.GetString("Degree_Insert", resourceCulture);
			}
		}


		public static string Degree_List
		{
			get
			{
				return ResourceManager.GetString("Degree_List", resourceCulture);
			}
		}


		public static string Degree_Update
		{
			get
			{
				return ResourceManager.GetString("Degree_Update", resourceCulture);
			}
		}
		#endregion
		#region Duration

		public static string Duration_Delete
		{
			get
			{
				return ResourceManager.GetString("Duration_Delete", resourceCulture);
			}
		}


		public static string Duration_Id
		{
			get
			{
				return ResourceManager.GetString("Duration_Id", resourceCulture);
			}
		}


		public static string Duration_Insert
		{
			get
			{
				return ResourceManager.GetString("Duration_Insert", resourceCulture);
			}
		}


		public static string Duration_List
		{
			get
			{
				return ResourceManager.GetString("Duration_List", resourceCulture);
			}
		}


		public static string Duration_Update
		{
			get
			{
				return ResourceManager.GetString("Duration_Update", resourceCulture);
			}
		}
		#endregion


		#region Platoon

		public static string Platoon_Delete
		{
			get
			{
				return ResourceManager.GetString("Platoon_Delete", resourceCulture);
			}
		}


		public static string Platoon_Id
		{
			get
			{
				return ResourceManager.GetString("Platoon_Id", resourceCulture);
			}
		}


		public static string Platoon_Insert
		{
			get
			{
				return ResourceManager.GetString("Platoon_Insert", resourceCulture);
			}
		}


		public static string Platoon_List
		{
			get
			{
				return ResourceManager.GetString("Platoon_List", resourceCulture);
			}
		}


		public static string Platoon_Update
		{
			get
			{
				return ResourceManager.GetString("Platoon_Update", resourceCulture);
			}
		}
		#endregion

		#region Qualification

		public static string Qualification_Delete
		{
			get
			{
				return ResourceManager.GetString("Qualification_Delete", resourceCulture);
			}
		}


		public static string Qualification_Id
		{
			get
			{
				return ResourceManager.GetString("Qualification_Id", resourceCulture);
			}
		}


		public static string Qualification_Insert
		{
			get
			{
				return ResourceManager.GetString("Qualification_Insert", resourceCulture);
			}
		}


		public static string Qualification_List
		{
			get
			{
				return ResourceManager.GetString("Qualification_List", resourceCulture);
			}
		}


		public static string Qualification_Update
		{
			get
			{
				return ResourceManager.GetString("Qualification_Update", resourceCulture);
			}
		}
		#endregion

		#region Rank

		public static string Rank_Delete
		{
			get
			{
				return ResourceManager.GetString("Rank_Delete", resourceCulture);
			}
		}


		public static string Rank_Id
		{
			get
			{
				return ResourceManager.GetString("Rank_Id", resourceCulture);
			}
		}


		public static string Rank_Insert
		{
			get
			{
				return ResourceManager.GetString("Rank_Insert", resourceCulture);
			}
		}


		public static string Rank_List
		{
			get
			{
				return ResourceManager.GetString("Rank_List", resourceCulture);
			}
		}


		public static string Rank_Update
		{
			get
			{
				return ResourceManager.GetString("Rank_Update", resourceCulture);
			}
		}
		#endregion

		#region Trade

		public static string Trade_Delete
		{
			get
			{
				return ResourceManager.GetString("Trade_Delete", resourceCulture);
			}
		}


		public static string Trade_Id
		{
			get
			{
				return ResourceManager.GetString("Trade_Id", resourceCulture);
			}
		}


		public static string Trade_Insert
		{
			get
			{
				return ResourceManager.GetString("Trade_Insert", resourceCulture);
			}
		}


		public static string Trade_List
		{
			get
			{
				return ResourceManager.GetString("Trade_List", resourceCulture);
			}
		}


		public static string Trade_Update
		{
			get
			{
				return ResourceManager.GetString("Trade_Update", resourceCulture);
			}
		}
		#endregion

		#region Training

		public static string Training_Delete
		{
			get
			{
				return ResourceManager.GetString("Training_Delete", resourceCulture);
			}
		}


		public static string Training_Id
		{
			get
			{
				return ResourceManager.GetString("Training_Id", resourceCulture);
			}
		}


		public static string Training_Insert
		{
			get
			{
				return ResourceManager.GetString("Training_Insert", resourceCulture);
			}
		}


		public static string Training_List
		{
			get
			{
				return ResourceManager.GetString("Training_List", resourceCulture);
			}
		}


		public static string Training_Update
		{
			get
			{
				return ResourceManager.GetString("Training_Update", resourceCulture);
			}
		}
		#endregion

		#region Unit

		public static string Unit_Delete
		{
			get
			{
				return ResourceManager.GetString("Unit_Delete", resourceCulture);
			}
		}


		public static string Unit_Id
		{
			get
			{
				return ResourceManager.GetString("Unit_Id", resourceCulture);
			}
		}


		public static string Unit_Insert
		{
			get
			{
				return ResourceManager.GetString("Unit_Insert", resourceCulture);
			}
		}


		public static string Unit_List
		{
			get
			{
				return ResourceManager.GetString("Unit_List", resourceCulture);
			}
		}


		public static string Unit_Update
		{
			get
			{
				return ResourceManager.GetString("Unit_Update", resourceCulture);
			}
		}
		#endregion

		#region Country

		public static string Country_Delete
		{
			get
			{
				return ResourceManager.GetString("Country_Delete", resourceCulture);
			}
		}


		public static string Country_Id
		{
			get
			{
				return ResourceManager.GetString("Country_Id", resourceCulture);
			}
		}


		public static string Country_Insert
		{
			get
			{
				return ResourceManager.GetString("Country_Insert", resourceCulture);
			}
		}


		public static string Country_List
		{
			get
			{
				return ResourceManager.GetString("Country_List", resourceCulture);
			}
		}


		public static string Country_Update
		{
			get
			{
				return ResourceManager.GetString("Country_Update", resourceCulture);
			}
		}
		#endregion

		#region MilitaryInstitution

		public static string MilitaryInstitution_Delete
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Delete", resourceCulture);
			}
		}


		public static string MilitaryInstitution_Id
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Id", resourceCulture);
			}
		}


		public static string MilitaryInstitution_Insert
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Insert", resourceCulture);
			}
		}


		public static string MilitaryInstitution_List
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_List", resourceCulture);
			}
		}


		public static string MilitaryInstitution_Update
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Update", resourceCulture);
			}
		}
		#endregion

		#region CivilInstitution

		public static string CivilInstitution_Delete
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Delete", resourceCulture);
			}
		}


		public static string CivilInstitution_Id
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Id", resourceCulture);
			}
		}


		public static string CivilInstitution_Insert
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Insert", resourceCulture);
			}
		}


		public static string CivilInstitution_List
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_List", resourceCulture);
			}
		}


		public static string CivilInstitution_Update
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Update", resourceCulture);
			}
		}
		#endregion

		#region Candidate

		public static string Candidate_Delete
		{
			get
			{
				return ResourceManager.GetString("Candidate_Delete", resourceCulture);
			}
		}


		public static string Candidate_Id
		{
			get
			{
				return ResourceManager.GetString("Candidate_Id", resourceCulture);
			}
		}


		public static string Candidate_Insert
		{
			get
			{
				return ResourceManager.GetString("Candidate_Insert", resourceCulture);
			}
		}


		public static string Candidate_List
		{
			get
			{
				return ResourceManager.GetString("Candidate_List", resourceCulture);
			}
		}


		public static string Candidate_Update
		{
			get
			{
				return ResourceManager.GetString("Candidate_Update", resourceCulture);
			}
		}
		#endregion


		#region CandidateCadre

		public static string CandidateCadre_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_Delete", resourceCulture);
			}
		}


		public static string CandidateCadre_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_Id", resourceCulture);
			}
		}


		public static string CandidateCadre_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_Insert", resourceCulture);
			}
		}


		public static string CandidateCadre_List
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_List", resourceCulture);
			}
		}


		public static string CandidateCadre_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_Update", resourceCulture);
			}
		}
		#endregion


		#region CandidateAddlQualification

		public static string CandidateAddlQualification_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_Delete", resourceCulture);
			}
		}


		public static string CandidateAddlQualification_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_Id", resourceCulture);
			}
		}


		public static string CandidateAddlQualification_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_Insert", resourceCulture);
			}
		}


		public static string CandidateAddlQualification_List
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_List", resourceCulture);
			}
		}


		public static string CandidateAddlQualification_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_Update", resourceCulture);
			}
		}
		#endregion

		#region CandidateAssultCourse

		public static string CandidateAssultCourse_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_Delete", resourceCulture);
			}
		}


		public static string CandidateAssultCourse_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_Id", resourceCulture);
			}
		}


		public static string CandidateAssultCourse_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_Insert", resourceCulture);
			}
		}


		public static string CandidateAssultCourse_List
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_List", resourceCulture);
			}
		}


		public static string CandidateAssultCourse_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_Update", resourceCulture);
			}
		}
		#endregion

		#region CandidateCertification

		public static string CandidateCertification_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_Delete", resourceCulture);
			}
		}


		public static string CandidateCertification_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_Id", resourceCulture);
			}
		}


		public static string CandidateCertification_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_Insert", resourceCulture);
			}
		}


		public static string CandidateCertification_List
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_List", resourceCulture);
			}
		}


		public static string CandidateCertification_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_Update", resourceCulture);
			}
		}
		#endregion

		#region CandidateCivilEducation

		public static string CandidateCivilEducation_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_Delete", resourceCulture);
			}
		}


		public static string CandidateCivilEducation_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_Id", resourceCulture);
			}
		}


		public static string CandidateCivilEducation_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_Insert", resourceCulture);
			}
		}


		public static string CandidateCivilEducation_List
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_List", resourceCulture);
			}
		}


		public static string CandidateCivilEducation_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_Update", resourceCulture);
			}
		}
		#endregion


		#region CandidateCompetition

		public static string CandidateCompetition_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_Delete", resourceCulture);
			}
		}


		public static string CandidateCompetition_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_Id", resourceCulture);
			}
		}


		public static string CandidateCompetition_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_Insert", resourceCulture);
			}
		}


		public static string CandidateCompetition_List
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_List", resourceCulture);
			}
		}


		public static string CandidateCompetition_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_Update", resourceCulture);
			}
		}
		#endregion

		#region CandidateDiscipline

		public static string CandidateDiscipline_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_Delete", resourceCulture);
			}
		}


		public static string CandidateDiscipline_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_Id", resourceCulture);
			}
		}


		public static string CandidateDiscipline_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_Insert", resourceCulture);
			}
		}


		public static string CandidateDiscipline_List
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_List", resourceCulture);
			}
		}


		public static string CandidateDiscipline_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_Update", resourceCulture);
			}
		}
		#endregion

		#region CandidateGPT

		public static string CandidateGPT_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_Delete", resourceCulture);
			}
		}


		public static string CandidateGPT_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_Id", resourceCulture);
			}
		}


		public static string CandidateGPT_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_Insert", resourceCulture);
			}
		}


		public static string CandidateGPT_List
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_List", resourceCulture);
			}
		}


		public static string CandidateGPT_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_Update", resourceCulture);
			}
		}
		#endregion
		#region CandidateIPFT

		public static string CandidateIPFT_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_Delete", resourceCulture);
			}
		}


		public static string CandidateIPFT_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_Id", resourceCulture);
			}
		}


		public static string CandidateIPFT_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_Insert", resourceCulture);
			}
		}


		public static string CandidateIPFT_List
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_List", resourceCulture);
			}
		}


		public static string CandidateIPFT_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_Update", resourceCulture);
			}
		}
		#endregion

		#region CandidateMilitaryTraining

		public static string CandidateMilitaryTraining_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_Delete", resourceCulture);
			}
		}


		public static string CandidateMilitaryTraining_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_Id", resourceCulture);
			}
		}


		public static string CandidateMilitaryTraining_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_Insert", resourceCulture);
			}
		}


		public static string CandidateMilitaryTraining_List
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_List", resourceCulture);
			}
		}


		public static string CandidateMilitaryTraining_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_Update", resourceCulture);
			}
		}
		#endregion

		#region CandidateQuizCompetition

		public static string CandidateQuizCompetition_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_Delete", resourceCulture);
			}
		}


		public static string CandidateQuizCompetition_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_Id", resourceCulture);
			}
		}


		public static string CandidateQuizCompetition_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_Insert", resourceCulture);
			}
		}


		public static string CandidateQuizCompetition_List
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_List", resourceCulture);
			}
		}


		public static string CandidateQuizCompetition_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_Update", resourceCulture);
			}
		}
		#endregion
		#region CandidateRET

		public static string CandidateRET_Delete
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_Delete", resourceCulture);
			}
		}


		public static string CandidateRET_Id
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_Id", resourceCulture);
			}
		}


		public static string CandidateRET_Insert
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_Insert", resourceCulture);
			}
		}


		public static string CandidateRET_List
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_List", resourceCulture);
			}
		}


		public static string CandidateRET_Update
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_Update", resourceCulture);
			}
		}
		#endregion
		#region Deshboard
		//
		public static string DeshboardData
		{
			get
			{
				return ResourceManager.GetString("DeshboardData", resourceCulture);
			}
		}
		#endregion
	}
}
