//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.API.Endpoint.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.API.Endpoint.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		///   Looks up a localized string similar to Invalid application log id: {0}..
		/// </summary>
		#region ApplicationLog
		public static string ApplicationLog_InvalidId {
            get {
                return ResourceManager.GetString("ApplicationLog_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application log page number: {0}..
        /// </summary>
        public static string ApplicationLog_InvalidPageNumber {
            get {
                return ResourceManager.GetString("ApplicationLog_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application log found with id: {0}..
        /// </summary>
        public static string ApplicationLog_NotFoundId {
            get {
                return ResourceManager.GetString("ApplicationLog_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application logs found..
        /// </summary>
        public static string ApplicationLog_NotFoundList {
            get {
                return ResourceManager.GetString("ApplicationLog_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application log is null..
        /// </summary>
        public static string ApplicationLog_Null {
            get {
                return ResourceManager.GetString("ApplicationLog_Null", resourceCulture);
            }
        }
		#endregion
		#region Audit Log
		/// <summary>
		///   Looks up a localized string similar to Invalid audit log id: {0}..
		/// </summary>
		public static string AuditLog_InvalidId {
            get {
                return ResourceManager.GetString("AuditLog_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audit log page number: {0}..
        /// </summary>
        public static string AuditLog_InvalidPageNumber {
            get {
                return ResourceManager.GetString("AuditLog_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audit log found with id: {0}..
        /// </summary>
        public static string AuditLog_NotFoundId {
            get {
                return ResourceManager.GetString("AuditLog_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audit logs found..
        /// </summary>
        public static string AuditLog_NotFoundList {
            get {
                return ResourceManager.GetString("AuditLog_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit log is null..
        /// </summary>
        public static string AuditLog_Null {
            get {
                return ResourceManager.GetString("AuditLog_Null", resourceCulture);
            }
        }
		#endregion
		#region Auth

		/// <summary>
		///   Looks up a localized string similar to Refresh token expired..
		/// </summary>
		public static string Auth_ExpiredRefreshToken {
            get {
                return ResourceManager.GetString("Auth_ExpiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string Auth_InvalidRefreshToken {
            get {
                return ResourceManager.GetString("Auth_InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login information is null..
        /// </summary>
        public static string Auth_LoginNull {
            get {
                return ResourceManager.GetString("Auth_LoginNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information is null..
        /// </summary>
        public static string Auth_UserInfoNull {
            get {
                return ResourceManager.GetString("Auth_UserInfoNull", resourceCulture);
            }
        }
		#endregion

		#region category
		/// <summary>
		///   Looks up a localized string similar to The category &apos;{0}&apos; already exists..
		/// </summary>
		public static string Category_Duplicate {
            get {
                return ResourceManager.GetString("Category_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category id: {0}..
        /// </summary>
        public static string Category_InvalidId {
            get {
                return ResourceManager.GetString("Category_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category page number: {0}..
        /// </summary>
        public static string Category_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Category_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id mismatch..
        /// </summary>
        public static string Category_Mismatch {
            get {
                return ResourceManager.GetString("Category_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
        /// </summary>
        public static string Category_NotFoundGetCategoriesWithPies {
            get {
                return ResourceManager.GetString("Category_NotFoundGetCategoriesWithPies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No category found with id: {0}..
        /// </summary>
        public static string Category_NotFoundId {
            get {
                return ResourceManager.GetString("Category_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found..
        /// </summary>
        public static string Category_NotFoundList {
            get {
                return ResourceManager.GetString("Category_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is null..
        /// </summary>
        public static string Category_Null {
            get {
                return ResourceManager.GetString("Category_Null", resourceCulture);
            }
        }

		#endregion

		#region Email
		/// <summary>
		///   Looks up a localized string similar to To, Subject or Body is empty. Property can not be empty..
		/// </summary>
		public static string Email_Empty {
            get {
                return ResourceManager.GetString("Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is null..
        /// </summary>
        public static string Email_Null {
            get {
                return ResourceManager.GetString("Email_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email template id: {0}..
        /// </summary>
        public static string EmailTemplate_InvalidId {
            get {
                return ResourceManager.GetString("EmailTemplate_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email template page number: {0}..
        /// </summary>
        public static string EmailTemplate_InvalidPageNumber {
            get {
                return ResourceManager.GetString("EmailTemplate_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Id mismatch..
        /// </summary>
        public static string EmailTemplate_Mismatch {
            get {
                return ResourceManager.GetString("EmailTemplate_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found with id: {0}..
        /// </summary>
        public static string EmailTemplate_NotFoundId {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found..
        /// </summary>
        public static string EmailTemplate_NotFoundList {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found with name: {0}..
        /// </summary>
        public static string EmailTemplate_NotFoundName {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTemplate is null..
        /// </summary>
        public static string EmailTemplate_Null {
            get {
                return ResourceManager.GetString("EmailTemplate_Null", resourceCulture);
            }
        }
		#endregion

		#region Mobile
		/// <summary>
		///   Looks up a localized string similar to Invalid hash provided..
		/// </summary>
		public static string InvalidHash {
            get {
                return ResourceManager.GetString("InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password information is null..
        /// </summary>
        public static string MobileAuth_ChangePasswordNull {
            get {
                return ResourceManager.GetString("MobileAuth_ChangePasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration information is null..
        /// </summary>
        public static string MobileAuth_RegisterNull {
            get {
                return ResourceManager.GetString("MobileAuth_RegisterNull", resourceCulture);
            }
        }
		#endregion

		#region Pie
		/// <summary>
		///   Looks up a localized string similar to The pie &apos;{0}&apos; already exists..
		/// </summary>
		public static string Pie_Duplicate {
            get {
                return ResourceManager.GetString("Pie_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie category id: {0}..
        /// </summary>
        public static string Pie_InvalidCategoryId {
            get {
                return ResourceManager.GetString("Pie_InvalidCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie id: {0}..
        /// </summary>
        public static string Pie_InvalidId {
            get {
                return ResourceManager.GetString("Pie_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie page number: {0}..
        /// </summary>
        public static string Pie_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Pie_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Id mismatch..
        /// </summary>
        public static string Pie_Mismatch {
            get {
                return ResourceManager.GetString("Pie_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pie found with category id: {0}..
        /// </summary>
        public static string Pie_NotFoundCategoryId {
            get {
                return ResourceManager.GetString("Pie_NotFoundCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pie found with id: {0}..
        /// </summary>
        public static string Pie_NotFoundId {
            get {
                return ResourceManager.GetString("Pie_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pies found..
        /// </summary>
        public static string Pie_NotFoundList {
            get {
                return ResourceManager.GetString("Pie_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie is null..
        /// </summary>
        public static string Pie_Null {
            get {
                return ResourceManager.GetString("Pie_Null", resourceCulture);
            }
        }
		#endregion

		#region Sms
		/// <summary>
		///   Looks up a localized string similar to To or Content is empty. Property can not be empty..
		/// </summary>
		public static string SMS_Empty {
            get {
                return ResourceManager.GetString("SMS_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS is null..
        /// </summary>
        public static string SMS_Null {
            get {
                return ResourceManager.GetString("SMS_Null", resourceCulture);
            }
        }
		#endregion

		#region Brigade
		public static string Brigade_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Brigade_Duplicate", resourceCulture);
			}
		}

		public static string Brigade_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Brigade_InvalidId", resourceCulture);
			}
		}

		public static string Brigade_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Brigade_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Brigade_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Brigade_Mismatch", resourceCulture);
			}
		}


		public static string Brigade_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Brigade_NotFoundId", resourceCulture);
			}
		}

		public static string Brigade_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Brigade_NotFoundList", resourceCulture);
			}
		}

		public static string Brigade_Null
		{
			get
			{
				return ResourceManager.GetString("Brigade_Null", resourceCulture);
			}
		}
		#endregion

		#region BIAnnual
		public static string BIAnnual_Duplicate
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Duplicate", resourceCulture);
			}
		}

		public static string BIAnnual_InvalidId
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_InvalidId", resourceCulture);
			}
		}

		public static string BIAnnual_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_InvalidPageNumber", resourceCulture);
			}
		}

		public static string BIAnnual_Mismatch
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Mismatch", resourceCulture);
			}
		}


		public static string BIAnnual_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_NotFoundId", resourceCulture);
			}
		}

		public static string BIAnnual_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_NotFoundList", resourceCulture);
			}
		}

		public static string BIAnnual_Null
		{
			get
			{
				return ResourceManager.GetString("BIAnnual_Null", resourceCulture);
			}
		}
		#endregion

		#region BAASection
		public static string BAASection_Duplicate
		{
			get
			{
				return ResourceManager.GetString("BAASection_Duplicate", resourceCulture);
			}
		}

		public static string BAASection_InvalidId
		{
			get
			{
				return ResourceManager.GetString("BAASection_InvalidId", resourceCulture);
			}
		}

		public static string BAASection_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("BAASection_InvalidPageNumber", resourceCulture);
			}
		}

		public static string BAASection_Mismatch
		{
			get
			{
				return ResourceManager.GetString("BAASection_Mismatch", resourceCulture);
			}
		}


		public static string BAASection_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("BAASection_NotFoundId", resourceCulture);
			}
		}

		public static string BAASection_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("BAASection_NotFoundList", resourceCulture);
			}
		}

		public static string BAASection_Null
		{
			get
			{
				return ResourceManager.GetString("BAASection_Null", resourceCulture);
			}
		}
		#endregion

		#region Certificate
		public static string Certificate_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Certificate_Duplicate", resourceCulture);
			}
		}

		public static string Certificate_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Certificate_InvalidId", resourceCulture);
			}
		}

		public static string Certificate_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Certificate_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Certificate_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Certificate_Mismatch", resourceCulture);
			}
		}


		public static string Certificate_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Certificate_NotFoundId", resourceCulture);
			}
		}

		public static string Certificate_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Certificate_NotFoundList", resourceCulture);
			}
		}

		public static string Certificate_Null
		{
			get
			{
				return ResourceManager.GetString("Certificate_Null", resourceCulture);
			}
		}
		#endregion

		#region CertificateAuthority
		public static string CertificateAuthority_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Duplicate", resourceCulture);
			}
		}

		public static string CertificateAuthority_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_InvalidId", resourceCulture);
			}
		}

		public static string CertificateAuthority_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_InvalidPageNumber", resourceCulture);
			}
		}

		public static string CertificateAuthority_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Mismatch", resourceCulture);
			}
		}


		public static string CertificateAuthority_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_NotFoundId", resourceCulture);
			}
		}

		public static string CertificateAuthority_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_NotFoundList", resourceCulture);
			}
		}

		public static string CertificateAuthority_Null
		{
			get
			{
				return ResourceManager.GetString("CertificateAuthority_Null", resourceCulture);
			}
		}
		#endregion
		
		#region Company
		public static string Company_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Company_Duplicate", resourceCulture);
			}
		}

		public static string Company_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Company_InvalidId", resourceCulture);
			}
		}

		public static string Company_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Company_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Company_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Company_Mismatch", resourceCulture);
			}
		}


		public static string Company_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Company_NotFoundId", resourceCulture);
			}
		}

		public static string Company_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Company_NotFoundList", resourceCulture);
			}
		}

		public static string Company_Null
		{
			get
			{
				return ResourceManager.GetString("Company_Null", resourceCulture);
			}
		}
		#endregion

		#region Course
		public static string Course_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Course_Duplicate", resourceCulture);
			}
		}

		public static string Course_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Course_InvalidId", resourceCulture);
			}
		}

		public static string Course_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Course_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Course_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Course_Mismatch", resourceCulture);
			}
		}


		public static string Course_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Course_NotFoundId", resourceCulture);
			}
		}

		public static string Course_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Course_NotFoundList", resourceCulture);
			}
		}

		public static string Course_Null
		{
			get
			{
				return ResourceManager.GetString("Course_Null", resourceCulture);
			}
		}
		#endregion

		#region Degree
		public static string Degree_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Degree_Duplicate", resourceCulture);
			}
		}

		public static string Degree_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Degree_InvalidId", resourceCulture);
			}
		}

		public static string Degree_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Degree_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Degree_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Degree_Mismatch", resourceCulture);
			}
		}


		public static string Degree_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Degree_NotFoundId", resourceCulture);
			}
		}

		public static string Degree_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Degree_NotFoundList", resourceCulture);
			}
		}

		public static string Degree_Null
		{
			get
			{
				return ResourceManager.GetString("Degree_Null", resourceCulture);
			}
		}
		#endregion

		#region Duration
		public static string Duration_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Duration_Duplicate", resourceCulture);
			}
		}

		public static string Duration_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Duration_InvalidId", resourceCulture);
			}
		}

		public static string Duration_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Duration_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Duration_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Duration_Mismatch", resourceCulture);
			}
		}


		public static string Duration_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Duration_NotFoundId", resourceCulture);
			}
		}

		public static string Duration_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Duration_NotFoundList", resourceCulture);
			}
		}

		public static string Duration_Null
		{
			get
			{
				return ResourceManager.GetString("Duration_Null", resourceCulture);
			}
		}
		#endregion

		#region Platoon
		public static string Platoon_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Platoon_Duplicate", resourceCulture);
			}
		}

		public static string Platoon_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Platoon_InvalidId", resourceCulture);
			}
		}

		public static string Platoon_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Platoon_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Platoon_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Platoon_Mismatch", resourceCulture);
			}
		}


		public static string Platoon_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Platoon_NotFoundId", resourceCulture);
			}
		}

		public static string Platoon_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Platoon_NotFoundList", resourceCulture);
			}
		}

		public static string Platoon_Null
		{
			get
			{
				return ResourceManager.GetString("Platoon_Null", resourceCulture);
			}
		}
		#endregion

		#region Qualification
		public static string Qualification_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Qualification_Duplicate", resourceCulture);
			}
		}

		public static string Qualification_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Qualification_InvalidId", resourceCulture);
			}
		}

		public static string Qualification_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Qualification_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Qualification_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Qualification_Mismatch", resourceCulture);
			}
		}


		public static string Qualification_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Qualification_NotFoundId", resourceCulture);
			}
		}

		public static string Qualification_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Qualification_NotFoundList", resourceCulture);
			}
		}

		public static string Qualification_Null
		{
			get
			{
				return ResourceManager.GetString("Qualification_Null", resourceCulture);
			}
		}
		#endregion

		#region Rank
		public static string Rank_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Rank_Duplicate", resourceCulture);
			}
		}

		public static string Rank_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Rank_InvalidId", resourceCulture);
			}
		}

		public static string Rank_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Rank_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Rank_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Rank_Mismatch", resourceCulture);
			}
		}


		public static string Rank_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Rank_NotFoundId", resourceCulture);
			}
		}

		public static string Rank_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Rank_NotFoundList", resourceCulture);
			}
		}

		public static string Rank_Null
		{
			get
			{
				return ResourceManager.GetString("Rank_Null", resourceCulture);
			}
		}
		#endregion

		#region Trade
		public static string Trade_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Trade_Duplicate", resourceCulture);
			}
		}

		public static string Trade_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Trade_InvalidId", resourceCulture);
			}
		}

		public static string Trade_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Trade_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Trade_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Trade_Mismatch", resourceCulture);
			}
		}


		public static string Trade_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Trade_NotFoundId", resourceCulture);
			}
		}

		public static string Trade_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Trade_NotFoundList", resourceCulture);
			}
		}

		public static string Trade_Null
		{
			get
			{
				return ResourceManager.GetString("Trade_Null", resourceCulture);
			}
		}
		#endregion

		#region Training
		public static string Training_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Training_Duplicate", resourceCulture);
			}
		}

		public static string Training_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Training_InvalidId", resourceCulture);
			}
		}

		public static string Training_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Training_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Training_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Training_Mismatch", resourceCulture);
			}
		}


		public static string Training_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Training_NotFoundId", resourceCulture);
			}
		}

		public static string Training_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Training_NotFoundList", resourceCulture);
			}
		}

		public static string Training_Null
		{
			get
			{
				return ResourceManager.GetString("Training_Null", resourceCulture);
			}
		}
		#endregion

		#region Unit
		public static string Unit_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Unit_Duplicate", resourceCulture);
			}
		}

		public static string Unit_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Unit_InvalidId", resourceCulture);
			}
		}

		public static string Unit_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Unit_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Unit_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Unit_Mismatch", resourceCulture);
			}
		}


		public static string Unit_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Unit_NotFoundId", resourceCulture);
			}
		}

		public static string Unit_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Unit_NotFoundList", resourceCulture);
			}
		}

		public static string Unit_Null
		{
			get
			{
				return ResourceManager.GetString("Unit_Null", resourceCulture);
			}
		}
		#endregion

		#region desboard
		public static string Deshboard_DataNotFound
		{
			get
			{
				return ResourceManager.GetString("Deshboard_DataNotFound", resourceCulture);
			}
		}
		#endregion

		#region Country
		public static string Country_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Country_Duplicate", resourceCulture);
			}
		}

		public static string Country_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Country_InvalidId", resourceCulture);
			}
		}

		public static string Country_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Country_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Country_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Country_Mismatch", resourceCulture);
			}
		}


		public static string Country_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Country_NotFoundId", resourceCulture);
			}
		}

		public static string Country_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Country_NotFoundList", resourceCulture);
			}
		}

		public static string Country_Null
		{
			get
			{
				return ResourceManager.GetString("Country_Null", resourceCulture);
			}
		}
		#endregion

		#region MilitaryInstitution
		public static string MilitaryInstitution_Duplicate
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Duplicate", resourceCulture);
			}
		}

		public static string MilitaryInstitution_InvalidId
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_InvalidId", resourceCulture);
			}
		}

		public static string MilitaryInstitution_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_InvalidPageNumber", resourceCulture);
			}
		}

		public static string MilitaryInstitution_Mismatch
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Mismatch", resourceCulture);
			}
		}


		public static string MilitaryInstitution_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_NotFoundId", resourceCulture);
			}
		}

		public static string MilitaryInstitution_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_NotFoundList", resourceCulture);
			}
		}

		public static string MilitaryInstitution_Null
		{
			get
			{
				return ResourceManager.GetString("MilitaryInstitution_Null", resourceCulture);
			}
		}
		#endregion
		
		#region CivilInstitution
		public static string CivilInstitution_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Duplicate", resourceCulture);
			}
		}

		public static string CivilInstitution_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_InvalidId", resourceCulture);
			}
		}

		public static string CivilInstitution_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_InvalidPageNumber", resourceCulture);
			}
		}

		public static string CivilInstitution_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Mismatch", resourceCulture);
			}
		}


		public static string CivilInstitution_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_NotFoundId", resourceCulture);
			}
		}

		public static string CivilInstitution_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_NotFoundList", resourceCulture);
			}
		}

		public static string CivilInstitution_Null
		{
			get
			{
				return ResourceManager.GetString("CivilInstitution_Null", resourceCulture);
			}
		}
		#endregion

		#region Candidate
		public static string Candidate_Duplicate
		{
			get
			{
				return ResourceManager.GetString("Candidate_Duplicate", resourceCulture);
			}
		}

		public static string Candidate_InvalidId
		{
			get
			{
				return ResourceManager.GetString("Candidate_InvalidId", resourceCulture);
			}
		}

		public static string Candidate_InvalidPageNumber
		{
			get
			{
				return ResourceManager.GetString("Candidate_InvalidPageNumber", resourceCulture);
			}
		}

		public static string Candidate_Mismatch
		{
			get
			{
				return ResourceManager.GetString("Candidate_Mismatch", resourceCulture);
			}
		}


		public static string Candidate_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("Candidate_NotFoundId", resourceCulture);
			}
		}

		public static string Candidate_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("Candidate_NotFoundList", resourceCulture);
			}
		}

		public static string Candidate_Null
		{
			get
			{
				return ResourceManager.GetString("Candidate_Null", resourceCulture);
			}
		}
		#endregion


		#region CandidateCadre
		public static string CandidateCadre_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_Duplicate", resourceCulture);
			}
		}

		public static string CandidateCadre_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_InvalidId", resourceCulture);
			}
		}


		public static string CandidateCadre_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_Mismatch", resourceCulture);
			}
		}


		public static string CandidateCadre_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateCadre_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateCadre_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateCadre_Null", resourceCulture);
			}
		}
		#endregion

		#region CandidateAddlQualification
		public static string CandidateAddlQualification_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_Duplicate", resourceCulture);
			}
		}

		public static string CandidateAddlQualification_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_InvalidId", resourceCulture);
			}
		}


		public static string CandidateAddlQualification_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_Mismatch", resourceCulture);
			}
		}


		public static string CandidateAddlQualification_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateAddlQualification_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateAddlQualification_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateAddlQualification_Null", resourceCulture);
			}
		}
		#endregion
		#region CandidateAssultCourse
		public static string CandidateAssultCourse_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_Duplicate", resourceCulture);
			}
		}

		public static string CandidateAssultCourse_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_InvalidId", resourceCulture);
			}
		}


		public static string CandidateAssultCourse_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_Mismatch", resourceCulture);
			}
		}


		public static string CandidateAssultCourse_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateAssultCourse_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateAssultCourse_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateAssultCourse_Null", resourceCulture);
			}
		}
		#endregion
		#region CandidateCertification
		public static string CandidateCertification_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_Duplicate", resourceCulture);
			}
		}

		public static string CandidateCertification_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_InvalidId", resourceCulture);
			}
		}


		public static string CandidateCertification_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_Mismatch", resourceCulture);
			}
		}


		public static string CandidateCertification_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateCertification_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateCertification_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateCertification_Null", resourceCulture);
			}
		}
		#endregion

		#region CandidateCivilEducation
		public static string CandidateCivilEducation_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_Duplicate", resourceCulture);
			}
		}

		public static string CandidateCivilEducation_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_InvalidId", resourceCulture);
			}
		}


		public static string CandidateCivilEducation_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_Mismatch", resourceCulture);
			}
		}


		public static string CandidateCivilEducation_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateCivilEducation_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateCivilEducation_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateCivilEducation_Null", resourceCulture);
			}
		}
		#endregion

		#region CandidateCompetition
		public static string CandidateCompetition_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_Duplicate", resourceCulture);
			}
		}

		public static string CandidateCompetition_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_InvalidId", resourceCulture);
			}
		}


		public static string CandidateCompetition_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_Mismatch", resourceCulture);
			}
		}


		public static string CandidateCompetition_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateCompetition_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateCompetition_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateCompetition_Null", resourceCulture);
			}
		}
		#endregion

		#region CandidateDiscipline
		public static string CandidateDiscipline_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_Duplicate", resourceCulture);
			}
		}

		public static string CandidateDiscipline_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_InvalidId", resourceCulture);
			}
		}


		public static string CandidateDiscipline_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_Mismatch", resourceCulture);
			}
		}


		public static string CandidateDiscipline_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateDiscipline_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateDiscipline_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateDiscipline_Null", resourceCulture);
			}
		}
		#endregion

		#region CandidateGPT
		public static string CandidateGPT_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_Duplicate", resourceCulture);
			}
		}

		public static string CandidateGPT_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_InvalidId", resourceCulture);
			}
		}


		public static string CandidateGPT_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_Mismatch", resourceCulture);
			}
		}


		public static string CandidateGPT_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateGPT_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateGPT_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateGPT_Null", resourceCulture);
			}
		}
		#endregion

		#region CandidateIPFT
		public static string CandidateIPFT_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_Duplicate", resourceCulture);
			}
		}

		public static string CandidateIPFT_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_InvalidId", resourceCulture);
			}
		}


		public static string CandidateIPFT_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_Mismatch", resourceCulture);
			}
		}


		public static string CandidateIPFT_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateIPFT_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateIPFT_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateIPFT_Null", resourceCulture);
			}
		}
		#endregion
		#region CandidateMilitaryTraining
		public static string CandidateMilitaryTraining_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_Duplicate", resourceCulture);
			}
		}

		public static string CandidateMilitaryTraining_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_InvalidId", resourceCulture);
			}
		}


		public static string CandidateMilitaryTraining_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_Mismatch", resourceCulture);
			}
		}


		public static string CandidateMilitaryTraining_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateMilitaryTraining_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateMilitaryTraining_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateMilitaryTraining_Null", resourceCulture);
			}
		}
		#endregion

		#region CandidateQuizCompetition
		public static string CandidateQuizCompetition_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_Duplicate", resourceCulture);
			}
		}

		public static string CandidateQuizCompetition_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_InvalidId", resourceCulture);
			}
		}


		public static string CandidateQuizCompetition_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_Mismatch", resourceCulture);
			}
		}


		public static string CandidateQuizCompetition_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateQuizCompetition_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateQuizCompetition_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateQuizCompetition_Null", resourceCulture);
			}
		}
		#endregion

		#region CandidateRET
		public static string CandidateRET_Duplicate
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_Duplicate", resourceCulture);
			}
		}

		public static string CandidateRET_InvalidId
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_InvalidId", resourceCulture);
			}
		}


		public static string CandidateRET_Mismatch
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_Mismatch", resourceCulture);
			}
		}


		public static string CandidateRET_NotFoundId
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_NotFoundId", resourceCulture);
			}
		}

		public static string CandidateRET_NotFoundList
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_NotFoundList", resourceCulture);
			}
		}

		public static string CandidateRET_Null
		{
			get
			{
				return ResourceManager.GetString("CandidateRET_Null", resourceCulture);
			}
		}
		#endregion
	}
}
